CREATE TABLE STUDENT(
   ID INT PRIMARY KEY NOT NULL,
   FIRSTNAME NVARCHAR(100) NOT NULL,
   LASTNAME NVARCHAR(100) NOT NULL,
   DATEOFBIRTH DATETIME NOT NULL,
   ENROLLEDDATE DATETIME NOT NULL,
   GENDER NCHAR NOT NULL,
   NATIONALIDNUMBER BIGINT NOT NULL,
   STUDENTCARDNUMBER INT NOT NULL
)

CREATE TABLE TEACHER(
   ID SMALLINT PRIMARY KEY NOT NULL,
   FIRSTNAME NVARCHAR(100) NOT NULL,
   LASTNAME NVARCHAR(100) NOT NULL,
   DATEOFBIRTH DATE NOT NULL,
   ACADEMICRANK NCHAR NOT NULL,
   HIREDATE DATE NOT NULL
)

CREATE TABLE GRADEDETAILS(
   ID INT PRIMARY KEY NOT NULL,
   GRADEID BIGINT NOT NULL,
   ACHIEVEMENTTYPEID INT NOT NULL,
   ACHIEVEMENTPOINTS INT NOT NULL,
   ACHIEVEMENTMAXPOINTS BIGINT NOT NULL,
   ACHIEVEMENTDATE DATETIME NOT NULL
)

CREATE TABLE COURSE(
   ID INT PRIMARY KEY NOT NULL,
   NAME NVARCHAR(30) NOT NULL,
   CREDIT INT NOT NULL,
   ACADEMICYEAR DATETIME NOT NULL,
   SEMESTER INT NOT NULL
)

CREATE TABLE GRADE(
   ID INT PRIMARY KEY NOT NULL,
   STUDENTID INT NOT NULL,
   COURSEID SMALLINT NOT NULL,
   TEACHERID SMALLINT NOT NULL,
   GRADE TINYINT NOT NULL,
   COMMENT NVARCHAR(100) NULL,
   CREATEDDATE DATETIME NOT NULL
)

CREATE TABLE ACHIEVEMENTTYPE(
   ID INT PRIMARY KEY NOT NULL,
   NAME NVARCHAR NOT NULL,
   DESCRIPTION NCHAR(50) NOT NULL,
   PARTICIPATIONRATE DECIMAL NOT NULL
)

SELECT GRADE FROM GRADE
WHERE GRADE >= 6

SELECT * FROM GRADEDETAILS 
WHERE ACHIEVEMENTMAXPOINTS = 100 

INSERT INTO STUDENT
VALUES (4528,'NIKOLA','GJORGJIEVSKI',1997/05/21,2015/09/15,'MALE',2105997460305,3457)

INSERT INTO TEACHER
VALUES (234,'MARINA','LAZAREVSKA','1970/06/21','PROFESSOR','2008/21/03')

